version: '3.8'

services:
  funpay_bot:
    build: .
    container_name: funpay_bot
    restart: always
    volumes:
      - .:/app
    working_dir: /app
    stdin_open: true
    tty: true
    command: ["python", "main.py"]
